arch:
#  - amd64
  - ppc64le
dist: bionic
language: java
before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential g++ wget git 
  - sudo apt forbid-version openjdk-8-jre-headless
